apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    run: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: account-service
    spec:
      containers:
      - name: account-service
        image: docker-release-local2.demo.jfrogchina.com/alexwang/account-service:latest
        ports:
        - containerPort: 2222
          protocol: TCP
      imagePullSecrets:
      - name: regcred
