apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30761
  selector:
    app: discovery-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-service
  labels:
    run: discovery-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: discovery-service
    spec:
      containers:
      - name: discovery-service
        image: docker-release-local2.demo.jfrogchina.com/sample-spring-microservices/discovery-service:latest
        ports:
        - containerPort: 8761
          protocol: TCP
      imagePullSecrets:
      - name: regcred 
